ehuigo/models/__init__.py
from .item import Manufacturer, Product, Question, Answer, ProductQuestion, ProductAnswer, Price, Category
from .account import User, UserStatus
from .order import Region, RecycleOrder, ExchangeOrder, Carrier

ehuigo/forms/__init__.py
from .account import RegisterForm, RegisterByEmailForm, UserProfileForm, UserSecurityForm, UserProfileCellphoneForm
from .order import RecycleOrderForm, TrackingAddForm

ehuigo/forms/order.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, SubmitField, IntegerField, FieldList, TextAreaField, SelectField
from wtforms.validators import InputRequired, Length, Email, EqualTo, Optional, Regexp, DataRequired, NumberRange
from wtforms import ValidationError

from ..models import Region
from ..constants import MAX_LENGTH, REG_EXP_PHONE, REG_EXP_TRACKING


class RecycleOrderForm(Form):
    service_type = SelectField('服务方式', coerce=int, validators=[DataRequired()], choices=[
        (0, '请选择服务方式'),
        (1, '上门服务'),
        (2, '邮寄服务'),
    ])
    fullname = StringField('姓名', validators=[
        InputRequired(),
        Length(1, MAX_LENGTH['fullname'], '长度不合法'),
        Regexp('[\u4e00-\u9fa5]+$', message='真实姓名中不能包含除简体汉字之外的字符')
    ])
    cellphone = StringField('手机号', validators=[
        InputRequired(),
        Length(1, MAX_LENGTH['cellphone'], '长度不合法'),
        Regexp(REG_EXP_PHONE, message='无效的手机号码')
    ])
    province = SelectField('省份', coerce=int, validators=[DataRequired()])
    city = SelectField('城市', coerce=int, validators=[DataRequired()])
    county = SelectField('县区', coerce=int)
    address = TextAreaField('详细地址', validators=[InputRequired()])
    remark = TextAreaField('备注')
    submit = SubmitField('提交')

    def validate_city(self, field):
        region = Region.query.get(field.data)
        if not region or region.parent_id != self.province.data:
            raise ValidationError('请重新选择')

    def validate_county(self, field):
        if len(self.county.choices) > 1:
            if not field.data:
                raise ValidationError('请选择县区')
            else:
                region = Region.query.get(field.data)
                if not region or region.parent_id != self.city.data:
                    raise ValidationError('请重新选择')


class TrackingAddForm(Form):
    tracking = StringField('快递单号', validators=[
        InputRequired(),
        Length(1, MAX_LENGTH['tracking'], '长度不合法'),
        Regexp(REG_EXP_TRACKING, message='无效的快递单号')
    ])
    carrier = SelectField('快递公司', validators=[DataRequired()])
    submit = SubmitField('邮寄')

ehuigo/__init__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import logging

from flask import Flask, render_template, request, jsonify
from flask.ext.sqlalchemy import get_debug_queries

from . import views
from .extensions import db, migrate, mail, login_manager, bootstrap
from .models import User

from config import config


def create_app(config_name):
    app = Flask(__name__)

    # config
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # logger
    init_app_logger(app)

    # blueprint
    app.register_blueprint(views.home)
    app.register_blueprint(views.account)
    app.register_blueprint(views.admin)
    app.register_blueprint(views.api)
    app.register_blueprint(views.order)

    # database & migrate
    db.init_app(app)
    migrate.init_app(app, db)

    # mail
    mail.init_app(app)

    login_manager.init_app(app)

    bootstrap.init_app(app)
    # print app.extensions['bootstrap']['cdns']

    config_request_handlers(app)
    config_error_handlers(app)

    return app


def init_app_logger(app):
    # logging

    file_handler = logging.FileHandler('flask.log')

    formatter = logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]'
    )

    file_handler.setFormatter(formatter)
    file_handler.setLevel(logging.DEBUG)
    app.logger.addHandler(file_handler)


def config_request_handlers(app):
    @app.before_request
    def before_request():
        pass
        # g.user = current_user

    @app.after_request
    def after_request(response):
        # 慢查询监视
        for query in get_debug_queries():
            if query.duration >= app.config['FLASK_SLOW_DB_QUERY_TIME']:
                app.logger.warning(
                    'Slow query: {0}\nParameters: {1}\nDuration: {2}\nContext: {3}\n'.format(
                        query.statement, query.parameters, query.duration, query.context
                    )
                )
        return response


def config_error_handlers(app):
    @app.errorhandler(400)
    def bad_request(e):
        if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
            response = jsonify({'error': 'bad request'})
            response.status_code = 400
            return response
        return render_template('error/400.html'), 400

    @app.errorhandler(404)
    def page_not_found(e):
        if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
            response = jsonify({'error': 'page not found'})
            response.status_code = 404
            return response
        return render_template('error/404.html'), 404

    @app.errorhandler(500)
    def internal_server_error(e):
        if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
            response = jsonify({'error': 'internal server error'})
            response.status_code = 500
            return response
        return render_template('error/500.html'), 500

ehuigo/views/__init__.py
from .home import home
from .account import account
from .admin import admin
from .api import api
from .order import order

ehuigo/views/home.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import io

from flask import Blueprint, render_template, request, jsonify, redirect, abort, current_app, send_from_directory, send_file, session
from flask.views import MethodView
from sqlalchemy.sql import func
from sqlalchemy import or_
from captcha.image import ImageCaptcha

from ..models import Manufacturer, Product
from ..helpers import send_sms, gen_captcha_str
from ..captcha import create_captcha


home = Blueprint('home', __name__)


@home.route('/')
def index():
    manufacturers = Manufacturer.query.limit(current_app.config['HOT_MANUFACTURER_NUM']).all()
    hot_products = Product.query.filter_by(for_recycle=True).limit(current_app.config['HOT_PRODUCT_NUM']).all()
    return render_template('index.html', manufacturers=manufacturers, hot_products=hot_products)


@home.route('/recycle/product/<int:product_id>/')
def show_recycle_product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.for_recycle:
        abort(404)
    return render_template('home/recycle/product_detail.html', product=product)


@home.route('/exchange/product/<int:product_id>/')
def show_exchange_product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.for_exchange:
        abort(404)
    return render_template('home/exchange/product_detail.html', product=product)


@home.route('/uploads/<filename>')
def send_upload_file(filename):
    if 'OSS_ENDPOINT' in current_app.config:
        url = 'http://' + current_app.config['OSS_ENDPOINT'] + '/' + filename
        return redirect(url)
    else:
        return send_from_directory(current_app.config['UPLOAD_PATH'], filename)


@home.route('/recycle/')
@home.route('/recycle/manufacturer/<int:manufacturer_id>/')
def show_recycle_products(manufacturer_id=None):
    if manufacturer_id:
        manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
        products = Product.query.filter_by(manufacturer_id=manufacturer_id, for_recycle=True).all()
    else:
        manufacturer = None
        products = Product.query.filter_by(for_recycle=True).all()
    return render_template('home/recycle/products.html', products=products, manufacturer=manufacturer)


@home.route('/recycle/search/', methods=['POST'])
def search_products():
    key = request.form.get('key')
    if not key:
        abort(400)
    search_string = '%{key}%'.format(key=key)
    products_1 = Product.query.filter(Product.model.like(search_string), Product.for_recycle==True)
    subqry = Manufacturer.query.filter(or_(Manufacturer.name.like(search_string), Manufacturer.alias.like(search_string))).subquery()
    products_2 = Product.query.filter(Product.manufacturer_id==subqry.c.id, Product.for_recycle==True)
    products = products_1.union(products_2).all()
    
    return render_template('home/recycle/products_search.html', products=products, key=key)


@home.route('/exchange/')
@home.route('/exchange/manufacturer/<int:manufacturer_id>/')
def show_exchange_products(manufacturer_id=None):
    if manufacturer_id:
        manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
        products = Product.query.filter_by(manufacturer_id=manufacturer_id, for_exchange=True).all()
    else:
        manufacturer = None
        products = Product.query.filter_by(for_exchange=True).all()
    return render_template('home/exchange/products.html', products=products, manufacturer=manufacturer)


@home.route('/recycle/manufacturers/')
def show_recycle_manufacturers():
    subqry = Product.query.group_by(Product.manufacturer_id).having(func.bit_or(Product.for_recycle)!=False).subquery()
    # print subqry
    manufacturers = Manufacturer.query.join(subqry, Manufacturer.id==subqry.c.manufacturer_id).all()
    return render_template('home/recycle/manufacturers.html', manufacturers=manufacturers)


@home.route('/exchange/manufacturers/')
def show_exchange_manufacturers():
    subqry = Product.query.group_by(Product.manufacturer_id).having(func.bit_or(Product.for_exchange)!=False).subquery()
    # print subqry
    manufacturers = Manufacturer.query.join(subqry, Manufacturer.id==subqry.c.manufacturer_id).all()
    return render_template('home/exchange/manufacturers.html', manufacturers=manufacturers)


@home.route('/400/')
def test_error_400():
    abort(400)


@home.route('/404/')
def test_error_404():
    abort(404)


@home.route('/500/')
def test_error_500():
    abort(500)


@home.route('/captcha/image/')
def gen_image_captcha():
    # 防止恶意刷新
    # if 'image_captcha_req_count' in session:
    #     session['image_captcha_req_count'] += 1
    # else:
    #     session['image_captcha_req_count'] = 1
    #
    # if session['image_captcha_req_count'] > 10:
    #     abort(403)

    img, captcha_str = create_captcha(
        size=(80, 34), chars=gen_captcha_str(4), img_type="PNG",
        font_type="ehuigo/static/fonts/ALGER.TTF",
    )
    f = io.BytesIO()
    img.save(f, 'PNG')
    f.seek(0)
    # print captcha_str
    session['image_captcha'] = captcha_str.upper()
    return send_file(f, mimetype='image/png', cache_timeout=0)

    # image = ImageCaptcha(width=80, height=30, fonts=['ehuigo/static/fonts/ALGER.TTF'], font_sizes=(30, 25, 35 ))
    # f = image.generate(captcha_str)
    # return send_file(f, mimetype='image/png')

ehuigo/views/order.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import io
import datetime

from flask import Blueprint, render_template, request, jsonify, redirect, abort, current_app, send_from_directory, send_file, session, url_for, flash
from flask.ext.login import current_user, login_required
from sqlalchemy.sql import func
from sqlalchemy import or_
from captcha.image import ImageCaptcha

from ..models import Region, RecycleOrder, Carrier
from ..helpers import send_sms, gen_captcha_str, gen_order_number
from ..captcha import create_captcha
from ..forms import RecycleOrderForm, TrackingAddForm
from ..extensions import db


order = Blueprint('order', __name__, url_prefix='/order')


@order.route('/add/', methods=['GET', 'POST'])
@login_required
def add_order():
    if 'recycle' not in session:
        flash('页面已过期，请重新进行估价', 'danger')
        current_app.logger.error('Key recycle is not in app session')
        return redirect(url_for('home.index'))

    recycle_data = session['recycle']

    # 初始化 form
    form = RecycleOrderForm(fullname=current_user.fullname, cellphone=current_user.cellphone)
    if form.province.data == 0: form.province.data = None
    if form.city.data == 0: form.city.data = None
    if form.county.data == 0: form.county.data = None
    # 从数据库中动态获取选项
    provinces = Region.query.filter_by(parent_id=1).all()
    cities = Region.query.filter_by(parent_id=form.province.data).all()
    counties = Region.query.filter_by(parent_id=form.city.data).all()
    form.province.choices = [(0, '请选择省份')] + [(p.id, p.name) for p in provinces]
    form.city.choices = [(0, '请选择城市')] + [(c.id, c.name) for c in cities]
    form.county.choices = [(0, '请选择县区')] + [(c.id, c.name) for c in counties]

    if form.validate_on_submit():
        province = Region.query.get(form.province.data)
        city = Region.query.get(form.city.data)
        county = Region.query.get(form.county.data)
        recycle_order = RecycleOrder(
            order_number=gen_order_number(),
            service_type=form.service_type.data,
            remark=form.remark.data,
            user_id=current_user.id,
            fullname=form.fullname.data,
            cellphone=form.cellphone.data,
            address=province.name+city.name+county.name+form.address.data,
            eval_detail=recycle_data['detail'],
            eval_price=recycle_data['price'],
            product_id=recycle_data['product_id']
        )
        db.session.add(recycle_order)
        db.session.commit()
        session.pop('recycle')
        flash('订单创建成功', 'success')
        return redirect(url_for('order.show_orders'))

    return render_template(
        'order/order_add.html', form=form,
        product_id=recycle_data['product_id'], price=recycle_data['price'], detail=recycle_data['detail']
    )


@order.route('/orders/')
@login_required
def show_orders():
    orders = RecycleOrder.query.filter_by(user_id=current_user.id)
    return render_template('order/orders.html', orders=orders)


@order.route('/<int:order_id>/')
@login_required
def show_order_detail(order_id):
    order_ = RecycleOrder.query.get_or_404(order_id)
    if order_.user_id != current_user.id:
        abort(403)
    # return str(order_id)
    return render_template('order/order_detail.html', order=order_)


@order.route('/<int:order_id>/tracking/add/', methods=['GET', 'POST'])
@login_required
def add_tracking(order_id):
    order_ = RecycleOrder.query.get_or_404(order_id)
    if order_.user_id != current_user.id:
        abort(403)

    if not order_.can_send():
        abort(400)

    form = TrackingAddForm()
    carriers = Carrier.query.order_by(Carrier.priority.asc()).all()
    form.carrier.choices = [('', '请选择快递公司')] + [(c.name, c.name) for c in carriers]
    # print form.carrier.choices
    if form.validate_on_submit():
        # print form.tracking.data
        # print form.carrier.data
        order_.send(tracking=form.tracking.data, carrier=form.carrier.data)
        db.session.add(order_)
        db.session.commit()

        return redirect(url_for('order.show_order_detail', order_id=order_.id))

    return render_template('order/tracking_add.html', form=form, order=order_)


@order.route('/<int:order_id>/cancel/')
@login_required
def cancel_order(order_id):
    order = RecycleOrder.query.get_or_404(order_id)
    if order.user_id != current_user.id:
        abort(403)
    if not order.can_cancel():
        abort(400)

    order.cancel()
    db.session.add(order)
    db.session.commit()
    return redirect(url_for('order.show_order_detail', order_id=order.id))

ehuigo/templates/order/order_detail.html
{% extends '_base.html' %}
{% block subtitle %}订单详情{% endblock %}
{% block page_content %}
            <div class="row">

                {% set sider_active = 'orders' %}
                {% include 'account/_sider.html' %}

                <div class="col-md-9 col-sm-9">
                    <div class="row">
                        <div class="col-md-12">
                        <ol class="breadcrumb">
                            <li><a href="{{ url_for('order.show_orders') }}">订单管理</a></li>
                            <li class="active">{{ order.order_number }}</li>
                        </ol>
                        <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {% include '_flash.html' %}
                            <form class="form-horizontal" id="order-form">
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">订单号</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.order_number }}
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">品牌型号</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            <a href="{{ url_for('home.show_recycle_product_detail', product_id=order.product_id) }}">{{ order.product.manufacturer.name }} {{ order.product.model }}</a>
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">估价金额</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static" id="eval-price">
                                            {{ order.eval_price }}&emsp;<a href="javascript:void(0);" id="toggle-eval-detail">详情</a>
                                        </p>
                                        <p id="eval-detail" style="display: none;">
                                            {{ order.eval_detail|safe }}
                                        </p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-2 control-label">服务类型</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.get_service_type() }}
                                        </p>
                                    </div>
                                </div>
                                {#
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">用户名</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            <a>{{ order.user.username }}</a>
                                        </p>
                                    </div>
                                </div>
                                #}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">姓名</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.fullname }}
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">手机</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.cellphone }}
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">地址</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.address }}
                                        </p>
                                    </div>
                                </div>
                                {#
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">邮编</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.zip_code }}
                                        </p>
                                    </div>
                                </div>
                                #}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">备注</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.remark }}
                                        </p>
                                    </div>
                                </div>
                                {% if order.service_type == order.SERVICE_TYPE_ONLINE %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">快递</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.carrier }} {{ order.tracking }}
                                        </p>
                                    </div>
                                </div>
                                {% endif %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">状态</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.get_order_state() }}
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">创建时间</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.create_time }}
                                        </p>
                                    </div>
                                </div>
                                {% if order.service_type == order.SERVICE_TYPE_ONLINE %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">邮寄时间</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.send_time }}
                                        </p>
                                    </div>
                                </div>
                                {% endif %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">收件时间</label>
                                    <div class="col-sm-10">
                                        <p class="form-control-static">
                                            {{ order.receive_time }}
                                        </p>
                                    </div>
                                </div>
                                <div class="col-md-offset-2">
                                    {% if order.can_send() %}
                                    <a class="btn btn-primary" href="{{ url_for('order.add_tracking', order_id=order.id) }}">邮寄</a>&emsp;
                                    {% endif %}
                                    {% if order.can_cancel() %}
                                    <a class="btn btn-danger" href="{{ url_for('order.cancel_order', order_id=order.id) }}">取消订单</a>
                                    {% endif %}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

{% endblock %}
{% block page_scripts %}
<script>
$(document).ready(function() {
  $('#eval-detail').hide();
  $('#toggle-eval-detail').click(function () {
      if ($('#eval-detail').is(":hidden")) {
          $('#eval-detail').show(500);
      } else {
          $('#eval-detail').hide(500);
      }

  });
});
</script>
{% endblock %}

ehuigo/templates/order/orders.html
{% extends '_base.html' %}
{% block subtitle %}订单管理{% endblock %}
{% block page_content %}
  <div class="row">
    {% set sider_active = 'orders' %}
    {% include 'account/_sider.html' %}
    <div class="col-md-9 col-sm-9">
      <div class="row">
        <div class="col-md-12">
        <ol class="breadcrumb">
          <li><a>用户中心</a></li>
          <li class="active">订单管理</li>
        </ol>
        <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% include '_flash.html' %}
          <table class="table table-condensed">
            <thead>
              <tr>
                <th>#</th>
                <th>订单号</th>
                  <th>姓名</th>
                  <th>手机</th>
                  <th>类型</th>
                  <th>状态</th>
                  <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr>
                <th scope="row">{{ order.id }}</th>
                <td><a href="{{ url_for('order.show_order_detail', order_id=order.id) }}">{{ order.order_number }}</a></td>
                <td>{{ order.fullname }}</td>
                <td>{{ order.cellphone }}</td>
                <td>{{ order.get_service_type() }}</td>
                <td>{{ order.get_order_state() }}</td>
                <td>
                  {% if order.can_send() %}<a class="btn btn-xs btn-primary" href="{{ url_for('order.add_tracking', order_id=order.id) }}">邮寄</a>{% endif %}
                </td>
              {#
                <td{% if user.status.cellphone_confirmed %} class="success" title="已验证"{% endif %}>{{ user.cellphone }}</td>
                <td{% if user.status.email_confirmed %} class="success" title="已验证"{% endif %}>{{ user.email }}</td>
                <td>{% if user.status.is_admin %}管理员{% endif %}&nbsp;{% if user.status.banned %}封禁{% endif %}</td>
               #}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block page_scripts %}
<script>
    $(document).ready(function () {
    });
</script>
{% endblock %}

ehuigo/templates/order/tracking_add.html
{% extends '_base.html' %}
{% block subtitle %}邮寄{% endblock %}
{% block page_content %}
  <div class="row">
  {% set sider_active = 'orders' %}
  {% include 'account/_sider.html' %}
    <div class="col-md-9 col-sm-9">
      <div class="row">
        <div class="col-md-12">
          <ol class="breadcrumb">
            <li><a href="{{ url_for('order.show_orders') }}">订单管理</a></li>
            <li><a href="{{ url_for('order.show_order_detail', order_id=order.id) }}">{{ order.order_number }}</a></li>
            <li class="active">邮寄</li>
          </ol>
          <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
        {% include '_flash.html' %}
          <form class="form-horizontal" id="tracking-add-form" method="post" action="{{ url_for('order.add_tracking', order_id=order.id) }}">
            <div class="form-group{% if form.tracking.errors %} has-error{% endif %}">
              {{ form.tracking.label(class_='col-md-offset-2 col-md-2 col-xs-12 control-label') }}
              <div class="col-md-4">
                {{ form.tracking(class_='form-control') }}
              </div>
              <div class="col-md-offset-4 col-md-4">
                <p class="help-block">{{ ', '.join(form.tracking.errors) }}</p>
              </div>
            </div>

            <div class="form-group{% if form.carrier.errors %} has-error{% endif %}">
              {{ form.carrier.label(class_='col-md-offset-2 col-md-2 col-xs-12 control-label') }}
              <div class="col-md-4">
                {{ form.carrier(class_='form-control') }}
              </div>
              <div class="col-md-offset-4 col-md-4">
                <p class="help-block">{{ ', '.join(form.carrier.errors) }}</p>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-offset-4 col-md-4">
                {{ form.submit(class_='btn btn-success pull-left') }}
                <a class="btn btn-default pull-right" href="{{ url_for('order.show_order_detail', order_id=order.id) }}">取消</a>
                <div class="clearfix"></div>
              </div>
            </div>
            {{ form.hidden_tag() }}
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block page_scripts %}
<script>
$(document).ready(function() {

});
</script>
{% endblock %}