ehuigo/forms/__init__.py
from .account import RegisterForm, RegisterByEmailForm, UserProfileForm, UserSecurityForm, UserProfileCellphoneForm
from .order import RecycleOrderForm, TrackingAddForm

ehuigo/forms/order.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, SubmitField, IntegerField, FieldList, TextAreaField, SelectField
from wtforms.validators import InputRequired, Length, Email, EqualTo, Optional, Regexp, DataRequired, NumberRange
from wtforms import ValidationError

from ..models import Region
from ..constants import MAX_LENGTH, REG_EXP_PHONE, REG_EXP_TRACKING


class RecycleOrderForm(Form):
    service_type = SelectField('服务方式', coerce=int, validators=[DataRequired()], choices=[
        (0, '请选择服务方式'),
        (1, '上门服务'),
        (2, '邮寄服务'),
    ])
    fullname = StringField('姓名', validators=[
        InputRequired(),
        Length(1, MAX_LENGTH['fullname'], '长度不合法'),
        Regexp('[\u4e00-\u9fa5]+$', message='真实姓名中不能包含除简体汉字之外的字符')
    ])
    cellphone = StringField('手机号', validators=[
        InputRequired(),
        Length(1, MAX_LENGTH['cellphone'], '长度不合法'),
        Regexp(REG_EXP_PHONE, message='无效的手机号码')
    ])
    province = SelectField('省份', coerce=int, validators=[DataRequired()])
    city = SelectField('城市', coerce=int, validators=[DataRequired()])
    county = SelectField('县区', coerce=int)
    address = TextAreaField('详细地址', validators=[InputRequired()])
    remark = TextAreaField('备注')
    submit = SubmitField('提交')

    def validate_city(self, field):
        region = Region.query.get(field.data)
        if not region or region.parent_id != self.province.data:
            raise ValidationError('请重新选择')

    def validate_county(self, field):
        if len(self.county.choices) > 1:
            if not field.data:
                raise ValidationError('请选择县区')
            else:
                region = Region.query.get(field.data)
                if not region or region.parent_id != self.city.data:
                    raise ValidationError('请重新选择')


class TrackingAddForm(Form):
    tracking = StringField('快递单号', validators=[
        InputRequired(),
        Length(1, MAX_LENGTH['tracking'], '长度不合法'),
        Regexp(REG_EXP_TRACKING, message='无效的快递单号')
    ])
    carrier = SelectField('快递公司', validators=[DataRequired()])
    submit = SubmitField('邮寄')

ehuigo/__init__.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import logging

from flask import Flask, render_template, request, jsonify
from flask.ext.sqlalchemy import get_debug_queries

from . import views
from .extensions import db, migrate, mail, login_manager, bootstrap
from .models import User

from config import config


def create_app(config_name):
    app = Flask(__name__)

    # config
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # logger
    init_app_logger(app)

    # blueprint
    app.register_blueprint(views.home)
    app.register_blueprint(views.account)
    app.register_blueprint(views.admin)
    app.register_blueprint(views.api)
    app.register_blueprint(views.order)

    # database & migrate
    db.init_app(app)
    migrate.init_app(app, db)

    # mail
    mail.init_app(app)

    login_manager.init_app(app)

    bootstrap.init_app(app)
    # print app.extensions['bootstrap']['cdns']

    config_request_handlers(app)
    config_error_handlers(app)

    return app


def init_app_logger(app):
    # logging

    file_handler = logging.FileHandler('flask.log')

    formatter = logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]'
    )

    file_handler.setFormatter(formatter)
    file_handler.setLevel(logging.DEBUG)
    app.logger.addHandler(file_handler)


def config_request_handlers(app):
    @app.before_request
    def before_request():
        pass
        # g.user = current_user

    @app.after_request
    def after_request(response):
        # 慢查询监视
        for query in get_debug_queries():
            if query.duration >= app.config['FLASK_SLOW_DB_QUERY_TIME']:
                app.logger.warning(
                    'Slow query: {0}\nParameters: {1}\nDuration: {2}\nContext: {3}\n'.format(
                        query.statement, query.parameters, query.duration, query.context
                    )
                )
        return response


def config_error_handlers(app):
    @app.errorhandler(400)
    def bad_request(e):
        if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
            response = jsonify({'error': 'bad request'})
            response.status_code = 400
            return response
        return render_template('error/400.html'), 400

    @app.errorhandler(404)
    def page_not_found(e):
        if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
            response = jsonify({'error': 'page not found'})
            response.status_code = 404
            return response
        return render_template('error/404.html'), 404

    @app.errorhandler(500)
    def internal_server_error(e):
        if request.accept_mimetypes.accept_json and not request.accept_mimetypes.accept_html:
            response = jsonify({'error': 'internal server error'})
            response.status_code = 500
            return response
        return render_template('error/500.html'), 500

ehuigo/views/__init__.py
from .home import home
from .account import account
from .admin import admin
from .api import api
from .order import order

ehuigo/views/account.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask import Blueprint, redirect, request, url_for, render_template, session, flash, abort, current_app
from flask.ext.login import login_user, logout_user, login_required, current_user
from sqlalchemy import or_

from ..models import User, UserStatus
from ..forms import RegisterForm, RegisterByEmailForm, UserProfileForm, UserSecurityForm, UserProfileCellphoneForm
from ..extensions import db
from ..helpers import send_email, get_client_ip, create_uploader


account = Blueprint('account', __name__, url_prefix='/account')


@account.route('/login/', methods=['GET', 'POST'])
def login():
    # 已登录用户则返回首页
    if current_user.is_authenticated:
        return redirect(request.args.get('next') or url_for('admin.index'))

    if request.method == 'POST':
        login_name = request.form.get('login-name')
        password = request.form.get('password')
        user = User.query.filter(or_(User.email==login_name, User.cellphone==login_name, User.username==login_name)).first()
        # print user
        next_ = session.pop('next', None)
        if user and user.verify_password(password):
            login_user(user)
            return redirect(next_ or url_for('admin.index'))
        else:
            flash('用户名或密码错误', 'danger')
            return redirect(url_for('account.login', next=next_))
    session['next'] = request.args.get('next')
    return render_template('account/login.html')


@account.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home.index'))


@account.route('/register/', methods=['GET', 'POST'])
def register():
    """通过手机号注册"""
    # 已登录用户则返回首页
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            # email=form.email.data,
            # username=form.username.data,
            password=form.password.data,
            cellphone=form.cellphone.data,
            reg_ip=get_client_ip(),
            status=UserStatus(cellphone_confirmed=True)
        )
        db.session.add(user)
        db.session.commit()
        # token = user.generate_activation_token()
        # send_email(user.email, '账户激活', 'mail/activation.html', user=user, token=token)
        # flash('注册成功，您的邮箱 {email} 将会收到一封激活邮件，请在一小时内查收邮件进行账户激活'.format(email=user.email), 'success')
        flash('注册成功', 'success')
        return redirect(url_for('account.login'))
    return render_template('account/register.html', form=form)


@account.route('/register/by_email/', methods=['GET', 'POST'])
def register_by_email():
    """通过邮箱注册"""
    # 已登录用户则返回首页
    if current_user.is_authenticated:
        return redirect(url_for('admin.index'))

    form = RegisterByEmailForm()
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            # username=form.username.data,
            password=form.password.data,
            # cellphone=form.cellphone.data,
            reg_ip=get_client_ip(),
            status=UserStatus()
        )
        db.session.add(user)
        db.session.commit()
        token = user.generate_activation_token()
        send_email(user.email, '账户激活', 'mail/activation.html', user=user, token=token)
        flash('注册成功，您的邮箱 {email} 将会收到一封激活邮件，请在一小时内查收邮件进行账户激活'.format(email=user.email), 'success')
        return redirect(url_for('account.login'))
    return render_template('account/register_by_email.html', form=form)


@account.route('/activate/')
def activate():
    token = request.args.get('token')
    data = User.load_activation_token(token)
    current_app.logger.debug(data)
    # print data
    if not data:
        flash('激活连接不合法或已失效', 'danger')
        return redirect(url_for('home.index'))

    user_id = data.get('user_id')
    user = User.query.get(user_id)
    if not user:
        flash('该账户还未注册', 'danger')
        return redirect(url_for('account.register'))

    if user.status.email_confirmed:
        flash('账户已激活，请勿重复激活', 'info')
        return redirect(url_for('home.index'))
    # elif user.status == USER_STATUS['frozen']:
    #     flash('账户已被冻结，无法激活', 'danger')

    user.status.email_confirmed = True
    # user_status = UserStatus.query.filter(user_id=user.id)
    db.session.add(user)
    db.session.commit()
    flash('账户激活成功', 'success')
    return redirect(url_for('account.login'))


@account.route('/activation/resend/')
@login_required
def resend_activation():
    token = current_user.generate_activation_token()
    send_email(current_user.email, '账户激活', 'mail/activation.html', user=current_user, token=token)
    flash('发送成功，您的邮箱 {email} 将会收到一封激活邮件，请在一小时内查收邮件进行账户激活'.format(email=current_user.email), 'success')
    return redirect(url_for('account.edit_profile'))


@account.route('/')
@login_required
def index():
    return redirect(url_for('account.edit_profile', user_id=current_user.id))


@account.route('/<int:user_id>/profile/edit/', methods=['GET', 'POST'])
@login_required
def edit_profile(user_id):
    if user_id != current_user.id:
        abort(403)
    user = User.query.get_or_404(user_id)
    form = UserProfileForm(obj=user)
    if form.validate_on_submit():
        user.username = form.username.data
        user.fullname = form.fullname.data
        user.alipay = form.alipay.data
        fs = form.avatar.data
        if fs:
            uploader = create_uploader()
            filename = uploader.save(fs)
            user.avatar = filename
        db.session.add(user)
        db.session.commit()

        flash('保存成功', 'success')
        return redirect(url_for('account.edit_profile', user_id=user_id))

    return render_template('account/profile_edit.html', form=form)


@account.route('/<int:user_id>/security/edit/', methods=['GET', 'POST'])
@login_required
def edit_security(user_id):
    if user_id != current_user.id:
        abort(403)

    user = User.query.get_or_404(user_id)
    form = UserSecurityForm(obj=user)
    if form.validate_on_submit():
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()

        flash('修改成功', 'success')
        return redirect(url_for('account.edit_security', user_id=user_id))

    return render_template('account/security_edit.html', form=form)


@account.route('/<int:user_id>/profile/cellphone/edit/', methods=['GET', 'POST'])
def edit_profile_cellphone(user_id):
    if user_id != current_user.id:
        abort(403)
    form = UserProfileCellphoneForm()
    if form.validate_on_submit():
        user = User.query.get_or_404(user_id)
        user.cellphone = form.cellphone.data
        user.status.cellphone_confirmed = True
        db.session.add(user)
        db.session.commit()
        flash('修改成功', 'success')
        return redirect(url_for('account.edit_profile', user_id=user_id))
    return render_template('account/profile_cellphone_edit.html', form=form)

ehuigo/views/home.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import io

from flask import Blueprint, render_template, request, jsonify, redirect, abort, current_app, send_from_directory, send_file, session
from flask.views import MethodView
from sqlalchemy.sql import func
from sqlalchemy import or_
from captcha.image import ImageCaptcha

from ..models import Manufacturer, Product
from ..helpers import send_sms, gen_captcha_str
from ..captcha import create_captcha


home = Blueprint('home', __name__)


@home.route('/')
def index():
    manufacturers = Manufacturer.query.limit(current_app.config['HOT_MANUFACTURER_NUM']).all()
    hot_products = Product.query.filter_by(for_recycle=True).limit(current_app.config['HOT_PRODUCT_NUM']).all()
    return render_template('index.html', manufacturers=manufacturers, hot_products=hot_products)


@home.route('/recycle/product/<int:product_id>/')
def show_recycle_product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.for_recycle:
        abort(404)
    return render_template('home/recycle/product_detail.html', product=product)


@home.route('/exchange/product/<int:product_id>/')
def show_exchange_product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.for_exchange:
        abort(404)
    return render_template('home/exchange/product_detail.html', product=product)


@home.route('/uploads/<filename>')
def send_upload_file(filename):
    if 'OSS_ENDPOINT' in current_app.config:
        url = 'http://' + current_app.config['OSS_ENDPOINT'] + '/' + filename
        return redirect(url)
    else:
        return send_from_directory(current_app.config['UPLOAD_PATH'], filename)


@home.route('/recycle/')
@home.route('/recycle/manufacturer/<int:manufacturer_id>/')
def show_recycle_products(manufacturer_id=None):
    if manufacturer_id:
        manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
        products = Product.query.filter_by(manufacturer_id=manufacturer_id, for_recycle=True).all()
    else:
        manufacturer = None
        products = Product.query.filter_by(for_recycle=True).all()
    return render_template('home/recycle/products.html', products=products, manufacturer=manufacturer)


@home.route('/recycle/search/', methods=['POST'])
def search_products():
    key = request.form.get('key')
    if not key:
        abort(400)
    search_string = '%{key}%'.format(key=key)
    products_1 = Product.query.filter(Product.model.like(search_string), Product.for_recycle==True)
    subqry = Manufacturer.query.filter(or_(Manufacturer.name.like(search_string), Manufacturer.alias.like(search_string))).subquery()
    products_2 = Product.query.filter(Product.manufacturer_id==subqry.c.id, Product.for_recycle==True)
    products = products_1.union(products_2).all()
    
    return render_template('home/recycle/products_search.html', products=products, key=key)


@home.route('/exchange/')
@home.route('/exchange/manufacturer/<int:manufacturer_id>/')
def show_exchange_products(manufacturer_id=None):
    if manufacturer_id:
        manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
        products = Product.query.filter_by(manufacturer_id=manufacturer_id, for_exchange=True).all()
    else:
        manufacturer = None
        products = Product.query.filter_by(for_exchange=True).all()
    return render_template('home/exchange/products.html', products=products, manufacturer=manufacturer)


@home.route('/recycle/manufacturers/')
def show_recycle_manufacturers():
    subqry = Product.query.group_by(Product.manufacturer_id).having(func.bit_or(Product.for_recycle)!=False).subquery()
    # print subqry
    manufacturers = Manufacturer.query.join(subqry, Manufacturer.id==subqry.c.manufacturer_id).all()
    return render_template('home/recycle/manufacturers.html', manufacturers=manufacturers)


@home.route('/exchange/manufacturers/')
def show_exchange_manufacturers():
    subqry = Product.query.group_by(Product.manufacturer_id).having(func.bit_or(Product.for_exchange)!=False).subquery()
    # print subqry
    manufacturers = Manufacturer.query.join(subqry, Manufacturer.id==subqry.c.manufacturer_id).all()
    return render_template('home/exchange/manufacturers.html', manufacturers=manufacturers)


@home.route('/400/')
def test_error_400():
    abort(400)


@home.route('/404/')
def test_error_404():
    abort(404)


@home.route('/500/')
def test_error_500():
    abort(500)


@home.route('/captcha/image/')
def gen_image_captcha():
    # 防止恶意刷新
    # if 'image_captcha_req_count' in session:
    #     session['image_captcha_req_count'] += 1
    # else:
    #     session['image_captcha_req_count'] = 1
    #
    # if session['image_captcha_req_count'] > 10:
    #     abort(403)

    img, captcha_str = create_captcha(
        size=(80, 34), chars=gen_captcha_str(4), img_type="PNG",
        font_type="ehuigo/static/fonts/ALGER.TTF",
    )
    f = io.BytesIO()
    img.save(f, 'PNG')
    f.seek(0)
    # print captcha_str
    session['image_captcha'] = captcha_str.upper()
    return send_file(f, mimetype='image/png', cache_timeout=0)

    # image = ImageCaptcha(width=80, height=30, fonts=['ehuigo/static/fonts/ALGER.TTF'], font_sizes=(30, 25, 35 ))
    # f = image.generate(captcha_str)
    # return send_file(f, mimetype='image/png')

ehuigo/templates/_base.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/fixes.html" as fixes %}
{% block html_attribs %} lang="zh-CN"{% endblock %}
{% block head %}
    {{super()}}
    {{fixes.ie8()}}
{% endblock %}
{% block metas %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta name="description" content="ehuigo">
    <meta name="keywords" content="ehuigo">
    <meta name="author" content="whypro">
{% endblock %}
{% block title %}{% block subtitle %}{% endblock %} | ehuigo{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/apple-touch-icon.png') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
{% endblock %}
{% block navbar %}
    <div class="container-fluid">
         {% include '_header.html' %}
    </div>
{% endblock navbar %}
{% block content %}
    <div class="container-fluid">
        {% block slider %}{% endblock %}
    </div>
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
    <div class="container">
        {% include '_footer.html' %}
    </div>
{% endblock content %}
{% block scripts %}
    {{ super() }}
    {% block page_scripts %}{% endblock %}
{% endblock %}

ehuigo/templates/_flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p class="text-center">{{ message }}</p>
    </div>
    {% endfor %}
{% endwith %}

ehuigo/templates/_footer.html
            <div class="row">
                <div class="col-md-12">
                    <hr />
                    <p class="text-center"><small>关于我们 · 联系我们 · 免责声明 · 帮助中心 · 移动应用</small></p>
                    <p class="text-center">
                        <small>&copy;2015 ehuigo.cn 版权所有</small>
                    </p>
                    <p class="text-center">
                        <small>西安龙玺网络科技有限公司 <a href="http://www.miitbeian.gov.cn/" target="_blank">陕ICP备15014467号</a></small>
                    </p>
                </div>
            </div>

ehuigo/templates/_header.html
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed toggle-button" data-toggle="collapse" data-target="#ehuigo-menu" aria-expanded="false">
                            <span class="sr-only">移动设备菜单</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-left brand-logo" href="{{ url_for('home.index') }}"><img src="{{ url_for('static', filename='images/logo.png') }}" /></a>
                        <a class="navbar-brand collapse" href="{{ url_for('home.index') }}">易回购</a>
                        
                        
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="ehuigo-menu">
                        <ul class="nav navbar-nav">
                            <li><a href="{{ url_for('home.show_recycle_manufacturers') }}">旧机回收</a></li>
                            <li><a href="{{ url_for('home.show_exchange_manufacturers') }}">以旧换新</a></li>
                            <li><a href="{{ url_for('home.index') }}">诚聘英才</a></li>
                            <li><a href="{{ url_for('home.index') }}">关于我们</a></li>
                            <li><a role="button" data-toggle="modal" data-target=".modal-go-mobile">手机易回购</a></li>

                            <div class="modal fade modal-go-mobile" tabindex="-1" role="dialog" aria-labelledby="modal-go-mobile-label">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                            <h4 class="modal-title" id="modal-go-mobile-labe">手机易回购</h4>

                                        </div>
                                        <div class="modal-body">
                                            <a href=""><img class="img-responsive" src="{{ url_for('static', filename='images/qr.png') }}"></a>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <li class="dropdown hidden">
                                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if current_user.is_authenticated -%}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">管理 <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url_for('account.edit_profile', user_id=current_user.id) }}">用户中心</a></li>
                                    {% if current_user.status.is_admin %}
                                    <li><a href="{{ url_for('admin.index') }}">管理中心</a></li>
                                    {% endif %}
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url_for('account.logout') }}">注销</a></li>
                                </ul>
                            </li>
                            {% else %}
                            <li><a href="{{ url_for('account.login') }}">登录</a></li>
                            <li><a href="{{ url_for('account.register') }}">注册</a></li>
                            {% endif %}
                        </ul>
                        <form class="navbar-form navbar-right hidden-sm" role="search" action="{{ url_for('home.search_products') }}" method="post">
                            <div class="form-group">
                                <div class="col-xs-8">
                                <label class="sr-only" for="key">Key</label>
                                <input name="key" type="text" class="form-control" placeholder="请输入手机型号……">
                                </div>
                                <div class="col-xs-4"><button type="submit" class="btn btn-default">搜索</button></div>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

ehuigo/templates/index.html
{% extends '_base.html' %}
{% block subtitle %}主页{% endblock %}
{% block slider %}
            <div class="row">
                <div class="col-md-12">
                    <div id="banner-carousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#banner-carousel" data-slide-to="0" class="active"></li>
                            <li data-target="#banner-carousel" data-slide-to="1"></li>
                            <li data-target="#banner-carousel" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="{{ url_for('static', filename='images/banner_1.jpg') }}" alt="carousel" width="100%">
                                <div class="carousel-caption">
                                ...
                                </div>
                            </div>
                            <div class="item">
                                <img src="{{ url_for('static', filename='images/banner_3.jpg') }}" alt="carousel" width="100%">
                                <div class="carousel-caption">
                                ...
                                </div>
                            </div>
                            <div class="item">
                                <img src="{{ url_for('static', filename='images/banner_2.jpg') }}" alt="carousel" width="100%">
                                <div class="carousel-caption">
                                ...
                                </div>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#banner-carousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#banner-carousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                    <hr>
                </div>
            </div>
{% endblock %}
{% block page_content %}
            <div class="row">
                {% include '_flash.html' %}
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>热门机型 <small><a href="{{ url_for('home.show_recycle_products') }}">[更多]</a></small></h3>
                    </div>
                </div>

                {% for product in hot_products %}
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumbnail">
                        <a href="{{ url_for('home.show_recycle_product_detail', product_id=product.id) }}">
                            <img alt="{{ product.model }}" src="{{ product.photo_url }}">
                        </a>
                        <div class="caption">
                            <h4>{{ product.model }}</h4>
                            <p>
                                <!-- 描述 -->
                            </p>
                            <p>
                                <span class="label label-danger">最高回收价：{{ product.price.recycle_max_price|int }} 元！</span>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>热门品牌 <small><a href="{{ url_for('home.show_recycle_manufacturers') }}">[更多]</a></small></h3>
                    </div>
                </div>

                {% for manufacturer in manufacturers %}
                <div class="col-md-2 col-sm-2 col-xs-4">
                    <a href="{{ url_for('home.show_recycle_products', manufacturer_id=manufacturer.id) }}" class="thumbnail">
                        <img alt="logo" src="{{ manufacturer.logo_url }}">
                    </a>
                </div>
                {% endfor %}
            </div>
{% endblock %}

ehuigo/templates/manufacturers_exchange.html
{% extends '_base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        <h3>所有品牌</h3>
                    </div>
                </div>

                {% for manufacturer in manufacturers %}
                <div class="col-md-2 col-sm-2 col-xs-4">
                    <a href="{{ url_for('home.show_exchange_products', manufacturer_id=manufacturer.id) }}" class="thumbnail">
                        <img alt="{{ manufacturer.name }}" src="{{ manufacturer.logo_url }}" />
                    </a>
                </div>
                {% endfor %}
            </div>
{% endblock %}