ehuigo/models/__init__.py
from .item import Manufacturer, Product, Question, Answer, ProductQuestion, ProductAnswer, Price, Category
from .account import User, UserStatus
from .order import Region, RecycleOrder, ExchangeOrder, Carrier

ehuigo/forms/__init__.py
from .account import RegisterForm, RegisterByEmailForm, UserProfileForm, UserSecurityForm, UserProfileCellphoneForm
from .order import RecycleOrderForm, TrackingAddForm

ehuigo/views/__init__.py
from .home import home
from .account import account
from .admin import admin
from .api import api
from .order import order

ehuigo/views/admin.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime

from flask import Blueprint, render_template, request, redirect, url_for, abort, flash, g, current_app
from flask.ext.login import login_required, current_user

from ..extensions import db
from ..models import Manufacturer, Product, Question, Answer, Category, User, RecycleOrder
from ..helpers import create_uploader, send_email
from ..constants import QUESTION_CATEGORY, QUESTION_CATEGORY_REVERSED

admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/')
@login_required
def index():
    # return render_template('admin/index.html')
    return redirect(url_for('admin.show_manufacturers'))


@admin.route('/manufacturers/')
@login_required
def show_manufacturers():
    manufacturers = Manufacturer.query.all()
    return render_template('admin/manufacturers.html', manufacturers=manufacturers)


@admin.route('/manufacturer/add/', methods=['POST'])
@login_required
def add_manufacturer():
    name = request.form.get('manufacturer-name')
    alias = request.form.get('manufacturer-alias')

    if not name:
        abort(400)

    # print name, alias
    filename = None
    fs = request.files.get('manufacturer-logo')
    if fs:
        uploader = create_uploader()
        filename = uploader.save(fs)

    manufacturer = Manufacturer(name=name, alias=alias, logo=filename)
    db.session.add(manufacturer)
    db.session.commit()

    flash('添加成功', 'success')
    return redirect(url_for('admin.show_manufacturers'))


@admin.route('/manufacturer/<int:manufacturer_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_manufacturer(manufacturer_id):
    manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
    if request.method == 'POST':
        name = request.form.get('manufacturer-name')
        alias = request.form.get('manufacturer-alias')

        if not name:
            abort(400)

        # print name, alias
        filename = None
        fs = request.files.get('manufacturer-logo')
        if fs:
            uploader = create_uploader()
            filename = uploader.save(fs)
            manufacturer.logo = filename

        manufacturer.name = name
        manufacturer.alias = alias

        db.session.add(manufacturer)
        db.session.commit()

        flash('保存成功', 'success')
        return redirect(url_for('admin.edit_manufacturer', manufacturer_id=manufacturer_id))

    return render_template('admin/manufacturer_detail.html', manufacturer=manufacturer)


@admin.route('/manufacturer/<int:manufacturer_id>/delete/')
@login_required
def delete_manufacturer(manufacturer_id):
    manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
    # remove manufacturer.logo
    # path = os.path.join(current_app.config['UPLOAD_PATH'], manufacturer.logo)
    # print path
    db.session.delete(manufacturer)
    db.session.commit()
    flash('删除成功', 'success')
    return redirect(url_for('admin.show_manufacturers'))


@admin.route('/manufacturer/<int:manufacturer_id>/products/')
@login_required
def show_products(manufacturer_id):
    manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
    products = Product.query.filter_by(manufacturer_id=manufacturer_id)
    return render_template('admin/products.html', products=products, manufacturer=manufacturer)


@admin.route('/product/add/', methods=['POST'])
@login_required
def add_product():
    current_app.logger.debug(request.form)
    # print request.form
    manufacturer_id = request.form.get('product-manufacturer')
    model = request.form.get('product-model')

    if not manufacturer_id or not model:
        abort(404)

    # print manufacturer_id, model
    filename = None
    fs = request.files.get('product-photo')
    if fs:
        uploader = create_uploader()
        filename = uploader.save(fs)

    manufacturer_id = int(manufacturer_id)
    manufacturer = Manufacturer.query.get_or_404(manufacturer_id)
    product = Product(manufacturer=manufacturer, model=model, version=None, photo=filename)
    db.session.add(product)
    db.session.commit()
    flash('添加成功', 'success')
    return redirect(url_for('admin.show_products', manufacturer_id=manufacturer_id))


@admin.route('/product/<int:product_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_product(product_id):
    product = Product.query.get_or_404(product_id)
    if request.method == 'POST':
        model = request.form.get('product-model')
        product.model = model
        category_id = int(request.form.get('product-category'))
        product.category_id = category_id if category_id else None

        fs = request.files.get('product-photo')
        if fs:
            uploader = create_uploader()
            filename = uploader.save(fs)
            product.photo = filename

        db.session.add(product)
        db.session.commit()

        flash('保存成功', 'success')
        return redirect(url_for('admin.edit_product', product_id=product_id))

    categories = Category.query.all()
    return render_template('admin/product_detail.html', product=product, categories=categories)


@admin.route('/product/<int:product_id>/delete/')
@login_required
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)
    manufacturer_id = product.manufacturer_id
    db.session.delete(product)
    db.session.commit()
    flash('删除成功', 'success')
    return redirect(url_for('admin.show_products', manufacturer_id=manufacturer_id))


@admin.route('/questions/', defaults={'category': 'recycle'})
@admin.route('/questions/<category>/')
@login_required
def show_questions(category):
    if category not in QUESTION_CATEGORY.keys():
        abort(404)
    questions = Question.query.filter_by(category=QUESTION_CATEGORY[category]).all()
    return render_template('admin/questions.html', questions=questions, category=category)


@admin.route('/question/add/', methods=['POST'])
@login_required
def add_question():
    question_content = request.form.get('question-content')
    question_remark = request.form.get('question-remark')
    answer_contents = request.form.getlist('answer-content[]')
    answer_remarks = request.form.getlist('answer-remark[]')
    category = request.form.get('category')
    if not question_content or not answer_contents or category not in QUESTION_CATEGORY.keys():
        abort(400)

    question = Question(content=question_content, remark=question_remark, category=QUESTION_CATEGORY[category])
    db.session.add(question)
    for i, content in enumerate(answer_contents):
        answer = Answer(question=question, content=content, remark=answer_remarks[i])
        db.session.add(answer)
    db.session.commit()

    flash('添加成功', 'success')
    return redirect(url_for('admin.show_questions', category=category))


@admin.route('/question/<int:question_id>/edit/', methods=['POST'])
@login_required
def edit_question(question_id):
    question_content = request.form.get('question-content')
    question_remark = request.form.get('question-remark')
    answer_ids = request.form.getlist('answer-id[]')
    answer_contents = request.form.getlist('answer-content[]')
    answer_remarks = request.form.getlist('answer-remark[]')
    if not question_content or not answer_contents:
        abort(400)

    question = Question.query.get_or_404(question_id)
    question.content = question_content
    question.remark = question_remark
    db.session.add(question)
    for i, content in enumerate(answer_contents):
        answer = Answer.query.get(answer_ids[i])
        if not answer:
            answer = Answer(question=question, content=content, remark=answer_remarks[i])
        else:
            answer.content = content
            answer.remark = answer_remarks[i]
        db.session.add(answer)
        
    db.session.commit()
    flash('保存成功', 'success')
    return redirect(url_for('admin.show_questions', category=QUESTION_CATEGORY_REVERSED[question.category]))


@admin.route('/question/<question_id>/delete/')
@login_required
def delete_question(question_id):
    question = Question.query.get_or_404(question_id)
    db.session.delete(question)
    db.session.commit()
    flash('删除成功', 'success')
    return redirect(url_for('admin.show_questions', category=QUESTION_CATEGORY_REVERSED[question.category]))


@admin.route('/product/<int:product_id>/recycle/edit/')
@login_required
def edit_recycle(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.for_recycle:
        # 未设置 for_recycle
        flash('请先选中旧机回收选项', 'warning')
        return redirect(url_for('admin.show_products', manufacturer_id=product.manufacturer_id))

    questions = Question.query.filter_by(category=QUESTION_CATEGORY['recycle']).all()
    discounts = dict()
    for product_answer in product.product_recycle_answers:
        discounts[product_answer.answer_id] = product_answer.discount
    # print discounts
    # [{'choices': [], 'price': int}]

    return render_template('admin/recycle.html', product=product, questions=questions, discounts=discounts)


def test_answers(questions, discounts):
    pass


def __travel(questions):
    """深度优先遍历"""
    pass


@admin.route('/product/<int:product_id>/exchange/edit/')
@login_required
def edit_exchange(product_id):
    product = Product.query.get_or_404(product_id)
    if not product.for_exchange:
        # 未设置 for_exchange
        flash('请先选中以旧换新选项', 'warning')
        return redirect(url_for('admin.show_products', manufacturer_id=product.manufacturer_id))

    questions = Question.query.filter_by(category=QUESTION_CATEGORY['exchange']).all()
    discounts = dict()
    for product_answer in product.product_exchange_answers:
        discounts[product_answer.answer_id] = product_answer.discount

    return render_template('admin/exchange.html', product=product, questions=questions, discounts=discounts)


@admin.route('/send_test_mail/')
@login_required
def send_test_mail():
    if current_user.email:

ehuigo/views/api.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re

from flask import Blueprint, jsonify, abort, flash, request, session, current_app
from flask.ext.login import login_required, current_user

from ..models import Question, Product, Price, ProductQuestion, ProductAnswer, Region, RecycleOrder
from ..extensions import db
from ..constants import QUESTION_CATEGORY, REG_EXP_PHONE
from ..helpers import gen_captcha_str, send_sms


api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/question/<int:question_id>/')
@login_required
def get_question(question_id):
    question = Question.query.get_or_404(question_id)
    question_dict = dict(id=question_id, content=question.content, remark=question.remark, answers=[])
    for answer in question.answers:
        question_dict['answers'].append(dict(id=answer.id, content=answer.content, remark=answer.remark))

    return jsonify(question_dict)


@api.route('/product/<int:product_id>/recycle/<action>/')
@login_required
def set_recycle_product(product_id, action):
    if action not in ('set', 'unset'):
        abort(400)

    p = Product.query.get_or_404(product_id)
    p.for_recycle = True if action == 'set' else False
    db.session.add(p)
    price = Price.query.filter_by(product_id=product_id).first()
    if action == 'set' and not price:
        price = Price(product_id=product_id)
        db.session.add(price)
    db.session.commit()

    return jsonify()


@api.route('/product/<int:product_id>/exchange/<action>/')
@login_required
def set_exchange_product(product_id, action):
    if action not in ('set', 'unset'):
        abort(400)

    p = Product.query.get_or_404(product_id)
    p.for_exchange = True if action == 'set' else False
    db.session.add(p)
    price = Price.query.filter_by(product_id=product_id).first()
    if action == 'set' and not price:
        price = Price(product_id=product_id)
        db.session.add(price)
    db.session.commit()

    return jsonify()


@api.route('/product/<int:product_id>/<category>/edit/', methods=['POST'])
@login_required
def edit_product_qa(product_id, category):
    if category not in QUESTION_CATEGORY.keys():
        abort(404)

    product = Product.query.get_or_404(product_id)
    data = request.get_json()
    # 删除
    if category == 'recycle':
        for product_question in product.product_recycle_questions:
            if product_question.id not in data['questions']:
                db.session.delete(product_question)
    elif category == 'exchange':
        for product_question in product.product_exchange_questions:
            if product_question.id not in data['questions']:
                db.session.delete(product_question)

    for order, question_id in enumerate(data['questions'], start=1):
        question_id = int(question_id)
        product_question = ProductQuestion.query.filter_by(product_id=product_id, question_id=question_id).first()
        if not product_question:
            product_question = ProductQuestion(product_id=product_id, question_id=question_id)
        product_question.order = order
        db.session.add(product_question)

    db.session.commit()

    for answer in data['answers']:
        answer_id = int(answer[0])
        discount = int(answer[1])
        product_answer = ProductAnswer.query.filter_by(product_id=product_id, answer_id=answer_id).first()
        if not product_answer:
            product_answer = ProductAnswer(product_id=product_id, answer_id=answer_id)
        product_answer.discount = discount
        db.session.add(product_answer)

    price = Price.query.filter_by(product_id=product_id).first()
    if not price:
        price = Price(product_id=product_id)

    if category == 'recycle':
        price.recycle_max_price = data['recycle_max_price']
        price.recycle_min_price = data['recycle_min_price']
    elif category == 'exchange':
        price.exchange_price = data['exchange_price']
        price.member_price = data['member_price']
        price.jd_price = data['jd_price']
        price.official_price = data['official_price']
        price.brief_intro = data['brief_intro']

    db.session.add(price)
    db.session.commit()
    flash('保存成功', 'success')
    return jsonify()


@api.route('/product/<int:product_id>/evaluate/', methods=['POST'])
def evaluate(product_id):
    product = Product.query.get_or_404(product_id)
    price = product.price.recycle_max_price
    min_price = product.price.recycle_min_price
    data = request.get_json()
    detail = ''
    for answer_id in data['answers']:
        product_answer = ProductAnswer.query.filter_by(product_id=product_id, answer_id=answer_id).one()
        price += product_answer.discount    # 加负等于减正
        detail += (product_answer.answer.question.content + '：' + product_answer.answer.content + '<br>')
    if price < min_price: price = min_price
    # print price
    # 设置 session
    recycle_data = dict(product_id=product_id, price=int(price), detail=detail)
    session['recycle'] = recycle_data
    return jsonify(price=int(price))


@api.route('/product/<int:product_id>/quote/', methods=['POST'])
def quote(product_id):
    product = Product.query.get_or_404(product_id)
    exchange_price = product.price.exchange_price
    member_price = product.price.member_price
    data = request.get_json()
    for answer_id in data['answers']:
        product_answer = ProductAnswer.query.filter_by(product_id=product_id, answer_id=answer_id).one()
        exchange_price += product_answer.discount    # 加负等于减正
        member_price += product_answer.discount    # 加负等于减正
    # current_app.logger.debug('{0} {1}'.format(exchange_price, member_price))
    # print exchange_price, member_price
    return jsonify(exchange_price=int(exchange_price), member_price=int(member_price))


@api.route('/captcha/sms/send/', methods=['POST'])
def send_sms_captcha():
    # import time
    # time.sleep(1)
    # return jsonify()
    SMS_CAPTCHA_TEMPLATE_ID = 1
    SMS_CAPTCHA_EXPIRE = 5
    data = request.get_json()
    cellphone = data['phone']
    image_captcha = data['image_captcha'].upper()
    # check phone
    if not re.match(REG_EXP_PHONE, cellphone):
        abort(400)

    # print image_captcha, session['image_captcha']
    if image_captcha != session.pop('image_captcha', None):
        abort(401)

    captcha_str = gen_captcha_str(6, digits_only=True)
    session['sms_captcha'] = dict(cellphone=cellphone, captcha=captcha_str.upper())
    resp_json = send_sms(
        [cellphone],
        template_id=SMS_CAPTCHA_TEMPLATE_ID,
        template_data=[captcha_str, SMS_CAPTCHA_EXPIRE]
    )
    return jsonify(resp_json)


@api.route('/region/<int:region_id>/children/')
def get_region_children(region_id):
    if region_id <= 0:
        return jsonify(regions=[])

    result = Region.query.filter_by(parent_id=region_id).all()
    region_children = [(r.id, r.name) for r in result]
    return jsonify(regions=region_children)

ehuigo/templates/home/recycle/manufacturers.html
{% extends '_base.html' %}
{% block subtitle %}所有品牌 | 旧机回收{% endblock %}
{% block page_content %}
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ url_for('home.show_recycle_manufacturers') }}">旧机回收</a></li>
                        <li class="active">所有品牌</li>
                    </ol>
                    <hr>
                </div>
            </div>
            <div class="row">
                {% for manufacturer in manufacturers %}
                <div class="col-md-2 col-sm-2 col-xs-4">
                    <a href="{{ url_for('home.show_recycle_products', manufacturer_id=manufacturer.id) }}" class="thumbnail">
                        <img alt="{{ manufacturer.name }}" src="{{ manufacturer.logo_url }}">
                    </a>
                </div>
                {% endfor %}
            </div>
{% endblock %}

ehuigo/templates/home/recycle/product_detail.html
{% extends '_base.html' %}
{% block subtitle %}{{ product.model }} | 旧机回收{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='jquery-labelauty.css') }}">
    <style>
        /*
        input.labelauty + label > span.labelauty-unchecked-image,
        input.labelauty + label > span.labelauty-checked-image
        {
            width: 16px;
            height: 30px;
        }

        input.labelauty + label > span.labelauty-unchecked,
        input.labelauty + label > span.labelauty-checked
        {
            line-height: 30px;
        }
        input.labelauty + label {
            font-size: 16px;
        }
        */
        input.labelauty + label {
            width: 100%;
            text-align: center;
        }

        input.labelauty:checked + label
        {
            background-color: #FF9900;
            color: #ffffff;
        }

        input.labelauty:checked:not([disabled]) + label:hover
        {
            background-color: #FFC700;
        }
        /*
        .control-label {
            font-size: 16px;
            line-height: 30px;
        }
        */
    </style>
{% endblock %}
{% block page_content %}
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ url_for('home.show_recycle_manufacturers') }}">旧机回收</a></li>
                        <li><a href="{{ url_for('home.show_recycle_products', manufacturer_id=product.manufacturer.id) }}">{{ product.manufacturer.name }}</a></li>
                        <li class="active">{{ product.model }}</li>
                    </ol>
                    <hr />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-9 col-sm-8 col-xs-12">
                        <form class="form-horizontal">
                            {% for question in product.recycle_questions %}
                            <div class="form-group">
                                <div class="row" style="border-bottom: 1px #ddd dashed;">
                                    <label class="col-md-2 col-sm-3 col-xs-12 control-label">{{ question.content }}</label>
                                    <div class="col-md-10 col-sm-9 col-xs-12">
                                        {% for answer in question.answers %}
                                        <div class="col-md-3 col-sm-6 col-xs-6">
                                            <input class="answer-input" type="radio" name="question-{{ question.id }}" id="answer-{{ answer.id }}" value="{{ answer.id }}" autocomplete="off"{% if not loop.index0 %} checked{% endif %} data-labelauty="{{ answer.content }}{% if answer.remark %}&nbsp;<small>（{{ answer.remark }}）</small>{% endif %}" answer-content="{{ answer.content }}">
                                            {# <span><small>{% if answer.remark %}（{{ answer.remark }}）{% endif %}</small></span> #}
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <hr />
                            <div class="form-group">
                                <div class="col-md-offset-2 col-sm-offset-3 col-md-10 col-sm-9 col-xs-12">
                                    <button type="button" class="btn btn-primary pull-left" id="evaluate-btn">立即估价</button>
                                    {% if current_user.is_authenticated() %}
                                    <a href="{{ url_for('admin.edit_recycle', product_id=product.id) }}" class="btn btn-warning pull-right">设置</a>
                                    {% endif %}
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-3 col-sm-4 col-xs-12">
                        <img class="img-responsive" alt="" src="{{ product.photo_url }}" />
                    </div>
                </div>

                <div id="show_evaluation_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="evaluation_report">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="evaluation_report">估价单</h4>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluid" id="evaluation_result">
                                    <p></p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <a href="{{ url_for('order.add_order') }}" class="btn btn-primary">确认无误，下一步</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
            </div>
{% endblock %}
{% block page_scripts %}
<script src="{{ url_for('static', filename='jquery-labelauty.js') }}"></script>
<script>
    $(document).ready(function(){
        $(".answer-input").labelauty();

        $("#evaluate-btn").click(function () {
            var answers = [];
            $("#evaluation_result p").empty();
            $("#evaluation_result p").append("品牌：{{ product.manufacturer.name }}<br>型号：{{ product.model }}<br>");
            $("input.answer-input:checked").each(function () {
                answers.push($(this).val());
                var question_content = $(this).parent().parent().prev("label").text();
                var answer_content = $(this).attr("answer-content");
                $("#evaluation_result p").append(question_content+"："+answer_content+"<br>");
            });
            console.log(answers);

            var data = JSON.stringify({'answers': answers});
            $.ajax({
                url: "{{ url_for('api.evaluate', product_id=product.id) }}",
                type: "POST",
                data: data,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // alert("success");
                    $("#evaluation_result p").append("<h4 class=\"text-danger\">估价结果："+data["price"]+"元</h4>");
                    $('#show_evaluation_modal').modal();
                }
            });
        });
        /*
        $(".answer-input").change(function () {
            var labels = $(this).parent().parent().children("label");
            labels.removeClass("btn-success");
            labels.addClass("btn-default");

            if ($(this).prop("checked")) {
                $(this).parent().removeClass("btn-default");
                $(this).parent().addClass("btn-success");
            }
            console.log($(this));
        });
        */

    });
</script>
{% endblock %}

ehuigo/templates/home/recycle/products.html
{% extends '_base.html' %}
{% block subtitle %}{{ manufacturer.name|d('所有产品') }} | 旧机回收{% endblock %}
{% block page_content %}
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ url_for('home.show_recycle_manufacturers') }}">旧机回收</a></li>
                        <li class="active">{{ manufacturer.name|d('所有产品') }}</li>
                    </ol>
                    <hr>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumbnail">
                        <a href="{{ url_for('home.show_recycle_product_detail', product_id=product.id) }}">
                            <img alt="{{ product.model }}" src="{{ product.photo_url }}">
                        </a>
                        <div class="caption">
                            <h4>{{ product.model }}</h4>
                            <p>
                                <!-- 描述 -->
                            </p>
                            <p>
                                <span class="label label-danger">最高价：{{ product.price.recycle_max_price|int }} 元！</span>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
{% endblock %}

ehuigo/templates/home/recycle/products_search.html
{% extends '_base.html' %}
{% block subtitle %}搜索结果 | 旧机回收{% endblock %}
{% block page_content %}
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{{ url_for('home.show_recycle_manufacturers') }}">旧机回收</a></li>
                        <li class="active">搜索结果</li>
                    </ol>
                    <hr>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumbnail">
                        <a href="{{ url_for('home.show_recycle_product_detail', product_id=product.id) }}">
                            <img alt="{{ product.model }}" src="{{ product.photo_url }}">
                        </a>
                        <div class="caption">
                            <h4>{{ product.model }}</h4>
                            <p>
                                <!-- 描述 -->
                            </p>
                            <p>
                                <span class="label label-danger">最高价：{{ product.price.recycle_max_price|int }} 元！</span>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

{% endblock %}